sudo: false

language:
  - php

addons:
    apt:
        packages:
            - oracle-java9-installer
  
php:
  - nightly
  - 7.1
  - 7.0
  - 5.6

matrix:
  allow_failures:
    - php: nightly

before_install:
    - ROOTWD=$(pwd)
    - mkdir extensions
    - cd extensions
    - chmod +x $ROOTWD/travis/scripts/shell/test.sh
    - $ROOTWD/travis/scripts/shell/test.sh

after_success:
    cd $ROOTWD
    tree
