sudo: false

language:
  - generic

addons:
    apt:
        packages:
            - oracle-java9-installer
            - tree
  
php:
  - nightly
  - 7.1
  - 7.0
  - 5.6

matrix:
  allow_failures:
    - php: nightly

before_install:
    - ROOTWD=$(pwd)
    - mkdir -p build/temp/extensions
    - cd build/temp/extensions
    - git clone https://github.com/jpbm04/organizer-plg_thm_organizer_search.git
    - git clone https://github.com/jpbm04/organizer-plg_thm_organizer_user.git
    - git clone https://github.com/jpbm04/organizer-plg_thm_organizer_editors_xtd_groups.git
    - git clone https://github.com/jpbm04/organizer-plg_thm_organizer_editors_xtd_subjects.git

after_success:
    cd $ROOTWD
    tree
