sudo: false

language:
  - php

addons:
    apt:
        packages:
            - oracle-java9-installer
  
php:
  - nightly
  - 7.1
  - 7.0
  - 5.6

matrix:
  allow_failures:
    - php: nightly

before_install:
    - ROOTWD=$(pwd)
    - cd ..
    - git clone git@github.com:jpbm04/organizer-plg_thm_organizer_search.git
    - git clone git@github.com:jpbm04/organizer-plg_thm_organizer_user.git
    - git clone git@github.com:jpbm04/organizer-plg_thm_organizer_editors_xtd_groups.git
    - git clone git@github.com:jpbm04/organizer-plg_thm_organizer_editors_xtd_subjects.git
    - tree
    - chmod +x $ROOTWD/travis/scripts/shell/test.sh
    - $ROOTWD/travis/scripts/shell/test.sh

after_success:
    cd $ROOTWD
    tree
