sudo: false

language:
  - php

addons:
    apt:
        packages:
            - oracle-java9-installer
  
php:
  - nightly
  - 7.1
  - 7.0
  - 5.6

matrix:
  allow_failures:
    - php: nightly

before_install:
    - chmod +x travis/scripts/shell/test.sh
    - travis/scripts/shell/test.sh
