sudo: false

language:
  - php

addons:
    apt:
        packages:
            - oracle-java9-installer
            - tree
  
php:
  - nightly
  - 7.1
  - 7.0
  - 5.6

matrix:
  allow_failures:
    - php: nightly

before_install:
    - ROOTWD=$(pwd)
    - cd ..
    - git clone https://github.com/jpbm04/organizer-plg_thm_organizer_search.git
    - git clone https://github.com/jpbm04/organizer-plg_thm_organizer_user.git
    - git clone https://github.com/jpbm04/organizer-plg_thm_organizer_editors_xtd_groups.git
    - git clone https://github.com/jpbm04/organizer-plg_thm_organizer_editors_xtd_subjects.git
    - ls -lah
    - tree
    - chmod +x $ROOTWD/organizer-com_thm_organizer/travis/scripts/shell/test.sh
    - $ROOTWD/organizer-com_thm_organizer/travis/scripts/shell/test.sh

after_success:
    cd $ROOTWD
    tree
